name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Load secrets from 1Password
      uses: 1Password/load-secrets-action/configure@v1.2.0
      with:
        connect-host: https://op.jpcdi.com/v1/vaults
        connect-token: ${{ secrets.OP_CONNECT_TOKEN }}

    - name: Load step-ca Credentials
      id: load-step-creds
      uses: 1password/load-secrets-action@v1.2.0
      with:
        export-env: false
      env:
        MARIADB_STEP_FINGERPRINT: op://dev/Smallstep/CertificateManager/JPCDI_Authority_Fingerprint
        MARIADB_STEP_URL: op://dev/Smallstep/CertificateManager/CA URL

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag step-linuxserver-mariadb:$(date +%s) --build-arg "CA_FINGERPRINT=${{ steps.load-step-ca-credentials.outputs.MARIADB_STEP_FINGERPRINT }}" --build-arg "CA_URL=${{ steps.load-step-ca-credentials.outputs.MARIADB_STEP_URL }}"
